### ISSUE TITLE
mixer with webpack

### ISSUE THREAD

**Issue by chinarui-na** [romlm/native-sound-mixer#1]
i use native-sound-mixer with vue. when i run project ,error appear:
![image](https://user-images.githubusercontent.com/55582739/112816249-c7c42b80-90b3-11eb-88ba-45b16a58d73e.png)
![image](https://user-images.githubusercontent.com/55582739/112816394-f215e900-90b3-11eb-960f-d2cd5c47ef6f.png)

native-sound-mixer with node is ok.
can you help me?

**Comment by romlm** [comment]
Hello,    This package is meant to be used server-side only, webpack cannot load a native compiled file, therefore, you may not include the package in any of your client-side files. If you have a mixed server/client package configuration, tell webpack not to compile this package. I ran into the same problems when I initially developed the package, as it is developed for Windows only, the compiled file cannot be correctly read by the browser (unless you do time-taking painfull and useless configuration) Provenance : Courrier pour Windows 10 De : chinarui-naEnvoyé le :lundi 29 mars 2021 11:27À : romlm/native-sound-mixerCc : SubscribedObjet :[romlm/native-sound-mixer] mixer with webpack (#1) i use native-sound-mixer with vue. when i run project ,error appear:native-sound-mixer with node is ok.can you help me?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. 



	
		
			
				
			
		
		
			
				L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
				www.avast.com
